name: CI_action

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 16.x, 22.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      # Backend
      - name: Install dependencies for backend
        run: |
          cd backend
          npm install

      - name: Run backend tests
        run: |
          cd backend
          npm test

      - name: Build backend
        run: |
          cd backend
          npm run build

      # Frontend
      - name: Install dependencies for frontend
        run: |
          cd frontend
          npm install

      #- name: Run frontend tests
      #  run: |
      #    cd frontend
      #    npm test # No testing setup for frontend just yet.

      - name: Build frontend
        run: |
          cd frontend
          npm run build
      
        
